### ISSUE TITLE
Javascript errors when option values have space

### ISSUE THREAD

**Issue by mmelendez21** [Eloar/bootstrap-tile-multiselect#1]
These lines of code throw errors when the option values have a space.  I added double quotes around the selector value to fix.  
Line 146 
`            $('option[value="' + elem.data('value') +'"]', this.$select).prop('selected', elem.hasClass('active')? 'selected' : false);`

Line 172
`                $('option[value="' + $(elem).data('value') +'"]', this.$select).removeAttr('selected');`

**Comment by Eloar** [comment]
I've not found it as I never tested it with texts in values. I used only numeric or hash identifiers as values with my control.

I've made change according to Your suggestion. Thanks for help. New version v0.0.6 is now available with this fix.
